# Dataset documentation

#' CIE Scotopic Luminous Efficiency Function
#'
#' The CIE scotopic luminous efficiency function V'(lambda) for night vision,
#' from CIE 018:2019 Table 2. Tabulated at 1 nm intervals from 380 nm to
#' 780 nm, with its peak at 507 nm. Used by \code{\link{scotopic_lux}}.
#'
#' @format A data frame with 401 rows and 2 columns:
#' \describe{
#'   \item{lambda}{Wavelength in standard air, in nm (380-780, step 1).}
#'   \item{W}{V'(lambda), dimensionless sensitivity from 0 to 1.}
#' }
#' @details Generated by \code{data-raw/build_cie_efficiency_data.R} from the
#'   checksum-pinned CIE CSV and companion metadata. Source URLs, DOI,
#'   checksums, retrieval date, standard, and license are stored as data-frame
#'   attributes under \code{"luxR.provenance"}.
#' @source International Commission on Illumination (CIE), \emph{CIE spectral
#'   luminous efficiency for scotopic vision}, DOI:
#'   \doi{10.25039/CIE.DS.gr6w4b5g}, licensed CC BY-SA 4.0.
"CIE_scotopic"

#' CIE Photopic Luminous Efficiency Function
#'
#' The CIE 1931 photopic luminous efficiency function V(lambda), also called
#' the standard observer luminosity curve, from CIE 018:2019 Table 1. Tabulated
#' at 1 nm intervals from 360 nm to 830 nm, with its peak at 555 nm.
#'
#' @format A data frame with 471 rows and 2 columns:
#' \describe{
#'   \item{lambda}{Wavelength in standard air, in nm (360-830, step 1).}
#'   \item{W}{V(lambda), dimensionless sensitivity from 0 to 1.}
#' }
#' @details Generated by \code{data-raw/build_cie_efficiency_data.R} from the
#'   checksum-pinned CIE CSV and companion metadata. Source URLs, DOI,
#'   checksums, retrieval date, standard, and license are stored as data-frame
#'   attributes under \code{"luxR.provenance"}.
#' @source International Commission on Illumination (CIE), \emph{CIE spectral
#'   luminous efficiency for photopic vision}, DOI:
#'   \doi{10.25039/CIE.DS.dktna2s3}, licensed CC BY-SA 4.0.
"CIE1931"

#' Example downwelling irradiance from Mare Chiaro, Gulf of Naples
#'
#' A small set of downwelling spectral irradiance measurements made at three
#' depths at Mare Chiaro in the Gulf of Naples, Italy. This is \strong{example
#' field data} — a single site on particular days — provided to illustrate
#' working with measured spectra; it is not a general reference spectrum (cf.
#' the ASTM \code{\link{solar_spectra}}). Values are in micromol photons per
#' square metre per second per nm (umol/m^2/s/nm); wavelength bins are
#' approximately 5 nm wide.
#'
#' @format A data frame with 103 rows and 4 columns:
#' \describe{
#'   \item{wv}{Bin-centre wavelength in nm.}
#'   \item{depth_0m}{Irradiance at the surface (0 m depth).}
#'   \item{depth_5m}{Irradiance at 5 m depth.}
#'   \item{depth_10m}{Irradiance at 10 m depth.}
#' }
#' @source Field measurements of downwelling spectral irradiance at Mare Chiaro,
#'   Gulf of Naples, Italy, attributed to M. J. Bok and J. D. Kirwan (2021,
#'   unpublished data). The bundled object is regenerated from an explicitly
#'   labelled legacy canonical snapshot; original acquisition metadata and
#'   redistribution terms are not documented.
#' @examples
#' data(Naples)
#' irradiance2lux(Naples$depth_0m, Naples$wv, photonic = TRUE, molar_unit = "umol")
"Naples"

#' Diffuse attenuation coefficients for Jerlov optical water types.
#'
#' Long-format table of Kd(lambda) values for five oceanic and three coastal
#' water types from Jerlov (1976) and Solonenko & Mobley (2015). Attributes
#' record the supported wavelength range and spacing, a table checksum, source
#' artifact path, build commit, model version, and package version.
#'
#' @format A data frame with 120 rows and 3 columns:
#' \describe{
#'   \item{type}{Jerlov water type (character): \code{"I"}, \code{"IA"},
#'     \code{"IB"}, \code{"II"}, \code{"III"} (oceanic, clearest to most
#'     turbid) and \code{"C1"}, \code{"C2"}, \code{"C3"} (coastal).}
#'   \item{lambda}{Wavelength in nm (350 to 700, 25 nm steps).}
#'   \item{Kd}{Diffuse attenuation coefficient in 1/m.}
#' }
#' @references
#'   Jerlov NG (1976) Marine Optics. Elsevier, Amsterdam.
#'
#'   Solonenko MG, Mobley CD (2015) Inherent and apparent optical
#'   properties of Jerlov water types. Applied Optics 54(17):5392-5401.
#' @examples
#' data(jerlov_types)
#' subset(jerlov_types, type == "IA")
"jerlov_types"

#' Photoreceptor spectral sensitivities for selected species.
#'
#' Peak wavelengths and chromophore types for visual photoreceptors of
#' representative species from vertebrate and invertebrate taxa.
#' Used by \code{\link{species_LEF}} and \code{\link{species_brightness}}.
#'
#' @format A data frame with 27 rows and 6 columns:
#' \describe{
#'   \item{species}{Scientific name.}
#'   \item{receptor}{Receptor class (e.g. \code{"L-cone"}, \code{"rod"}).}
#'   \item{lambda_max}{Peak absorbance wavelength in nm.}
#'   \item{chromophore}{\code{"A1"} (11-cis retinal) or \code{"A2"} (11-cis 3,4-didehydroretinal).}
#'   \item{channel_role}{Primary biological role from the controlled vocabulary
#'     \code{"chromatic"}, \code{"achromatic"}, \code{"irradiance"},
#'     \code{"polarization"}, or \code{"fluorescence"}.}
#'   \item{source}{Literature citation for the lambda_max value.}
#' }
#' @details
#'   Each row's \code{lambda_max} is taken from the primary-literature citation
#'   recorded in its \code{source} column; luxR reconstructs full sensitivity
#'   curves from these peaks using the Govardovskii et al. (2000) visual-pigment
#'   template (see \code{\link{govardovskii_template}}).
#'
#'   Per-receptor lambda_max sources: Bowmaker & Dartnall (1980) and Bailes &
#'   Lucas (2013) (\emph{Homo sapiens}); Robinson et al. (1993)
#'   (\emph{Danio rerio}); Peitsch et al. (1992) (\emph{Apis mellifera}); Salcedo
#'   et al. (1999) (\emph{Drosophila melanogaster}); Hart et al. (2004)
#'   (\emph{Callorhinchus milii}); Yokoyama et al. (1999) (\emph{Latimeria
#'   chalumnae}); Yoshiura et al. (2011) (\emph{Xenopus laevis}); Hawryshyn et
#'   al. (2003) (\emph{Oncorhynchus mykiss}).
#'
#'   A role label does not by itself validate a receptor for a model. Complete,
#'   cited channel memberships are recorded separately in
#'   \code{\link{species_channels}}. The generic mantis-shrimp record and
#'   \emph{Aequorea victoria} GFP previously included in this table were
#'   removed because they are not supported visual-pigment channel records.
#' @references
#'   Govardovskii VI, Fyhrquist N, Reuter T, Kuzmin DG, Donner K (2000) In
#'   search of the visual pigment template. Visual Neuroscience 17:509-528.
#'
#'   Full citation keys and their verification status are recorded in
#'   \code{data-raw/species_source_map.csv}. The legacy Hart et al. (2004) and
#'   Yoshiura et al. (2011) attributions remain explicitly unverified pending
#'   primary-source confirmation; the values are not silently relabelled.
#'
#'   \insertRef{robinsonZebrafishUltravioletVisual1993}{luxR}
#'
#'   \insertRef{hawryshynRegenerationUltravioletsensitiveCones2003}{luxR}
#'
#' @examples
#' data(species_sensitivities)
#' subset(species_sensitivities, species == "Danio rerio")
"species_sensitivities"

#' Validated visual-channel memberships for selected species.
#'
#' Defines cited receptor combinations that package models may use by default.
#' Receptors marked with a role in \code{\link{species_sensitivities}} are not
#' model-eligible unless they occur in this table.
#'
#' @format A data frame with 13 rows and 7 columns:
#' \describe{
#'   \item{species}{Scientific name matching
#'     \code{species_sensitivities$species}.}
#'   \item{channel}{Stable channel identifier within a species.}
#'   \item{channel_role}{Biological role from the controlled vocabulary.}
#'   \item{receptor}{Receptor member matching a species/receptor pair in
#'     \code{species_sensitivities}.}
#'   \item{weight}{Finite positive channel membership weight. Chromatic JND
#'     currently uses receptor-noise weighting rather than this field.}
#'   \item{is_default}{Whether this is the default channel for its species and
#'     role. A species can have at most one default channel per role.}
#'   \item{source}{Literature citation supporting the receptor set.}
#' }
#' @details
#'   The curated set contains default chromatic channels for \emph{Homo
#'   sapiens}, \emph{Danio rerio}, and \emph{Apis mellifera}, plus behavioural
#'   achromatic channels for adult light-adapted \emph{Danio rerio}, \emph{Apis
#'   mellifera}, and \emph{Drosophila melanogaster}.
#'   Species with incomplete or ambiguous receptor sets are deliberately absent
#'   and therefore fail rather than falling back to every known receptor.
#' @references
#'   Krauss A, Neumeyer C (2003) Wavelength dependence of the optomotor
#'   response in zebrafish (Danio rerio). Vision Research 43:1275-1284.
#'   \doi{10.1016/S0042-6989(03)00090-7}
#'
#'   Niggebrugge C, Hempel de Ibarra N (2003) Colour-dependent target detection
#'   by bees. Journal of Comparative Physiology A 189:915-918.
#'   \doi{10.1007/s00359-003-0466-3}
#'
#'   Yamaguchi S, Wolf R, Desplan C, Heisenberg M (2008) Motion vision is
#'   independent of color in Drosophila. PNAS 105:4910-4915.
#'   \doi{10.1073/pnas.0711484105}
#' @examples
#' data(species_channels)
#' subset(species_channels, species == "Homo sapiens")
"species_channels"

#' Species visual-channel support decisions.
#'
#' Records whether every bundled species has a supported default chromatic and
#' achromatic model. Unsupported combinations remain explicit rather than being
#' inferred from receptor-role labels.
#'
#' @format A data frame with 16 rows and 5 columns:
#' \describe{
#'   \item{species}{Scientific name matching \code{species_sensitivities}.}
#'   \item{channel_role}{Either \code{"chromatic"} or \code{"achromatic"}.}
#'   \item{status}{Either \code{"supported"} or \code{"unavailable"}.}
#'   \item{reason}{Evidence summary or reason no default is available.}
#'   \item{source}{Literature citation or explicit package review decision.}
#' }
#' @details Every supported row must correspond to exactly one default in
#'   \code{\link{species_channels}}. Every unavailable row must have no default.
#'   Dataset generation and runtime validation enforce this invariant.
#' @examples
#' data(species_channel_support)
#' subset(species_channel_support, species == "Homo sapiens")
"species_channel_support"

#' ASTM G173-03 reference solar spectral irradiance.
#'
#' A named list of reference spectral irradiance data frames representing
#' five standard illumination conditions, derived from the ASTM G173-03
#' global-tilt spectrum. Used by \code{\link{solar_irradiance}}.
#'
#' @format A named list of five data frames, each with columns:
#' \describe{
#'   \item{wavelength}{Wavelength in nm (300 to 800, step 10).}
#'   \item{irradiance}{Spectral irradiance in W/m^2/nm.}
#' }
#' Names: \code{clear_noon}, \code{clear_dawn}, \code{overcast},
#' \code{underwater_1m}, \code{underwater_10m}.
#' Each data frame has attributes \code{condition},
#' \code{reference_depth_m}, and \code{reference_medium}. Reference depth is
#' measured in metres from the water surface; the three atmospheric spectra
#' use depth 0 in \code{"air"}, and the underwater spectra use depths 1 and
#' 10 in \code{"water"}, respectively.
#' @source ASTM G173-03(2012) Standard Tables for Reference Solar Spectral
#'   Irradiances. American Society for Testing and Materials, West
#'   Conshohocken, PA.
#' @examples
#' solar_irradiance("clear_noon")
"solar_spectra"
